[package]
name    = "auction_engine"
version.workspace = true
edition.workspace = true

[dependencies]
common.path      = "../common"
db.path          = "../db"
chain.path       = "../chain"
orchestrator.path = "../orchestrator"

tokio.workspace      = true
tokio-util.workspace = true
tracing.workspace    = true
thiserror.workspace  = true
rust_decimal.workspace = true
uuid.workspace       = true
chrono.workspace     = true
rust_decimal_macros.workspace = true
